/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'van-lengths': VanLength;
    'floor-plans': FloorPlan;
    'trim-packages': TrimPackage;
    products: Product;
    categories: Category;
    'color-groups': ColorGroup;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'van-lengths': VanLengthsSelect<false> | VanLengthsSelect<true>;
    'floor-plans': FloorPlansSelect<false> | FloorPlansSelect<true>;
    'trim-packages': TrimPackagesSelect<false> | TrimPackagesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'color-groups': ColorGroupsSelect<false> | ColorGroupsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "van-lengths".
 */
export interface VanLength {
  id: number;
  /**
   * What the length gets the buyer, not the spec. Nobody arrives knowing they want 170 inches.
   */
  name: string;
  /**
   * Generated from the name when you first save. Permanent: shared build links encode it.
   */
  slug?: string | null;
  /**
   * The spec, e.g. 170" wheelbase, room for a fixed bed.
   */
  tagline: string;
  /**
   * What this length ADDS over the shortest van. The shortest one is 0.
   */
  priceDelta: number;
  image?: (number | null) | Media;
  /**
   * Overall vehicle length in inches. Drives the to-scale comparison bar.
   */
  overallInches: number;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the photo shows. Read aloud by screen readers.
   */
  alt: string;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "floor-plans".
 */
export interface FloorPlan {
  id: number;
  name: string;
  /**
   * Generated from the name when you first save. Permanent: shared build links encode it.
   */
  slug?: string | null;
  tagline: string;
  /**
   * Includes the Mercedes Sprinter itself. Every price surface in the app says so.
   */
  basePrice: number;
  order: number;
  /**
   * Which chassis this plan is built on. Leave empty for all of them.
   */
  availableLengths?: (number | VanLength)[] | null;
  /**
   * The layout gallery. First entry is the one shown on the floor plan card.
   */
  gallery?:
    | {
        label: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Essential, Adventure, Summit. A trim package pre-selects products from the shared library; it does not own them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trim-packages".
 */
export interface TrimPackage {
  id: number;
  name: string;
  /**
   * Generated from the name when you first save. Permanent: shared build links encode it.
   */
  slug?: string | null;
  tagline: string;
  /**
   * Added on top of the floor plan base price.
   */
  priceDelta: number;
  order: number;
  /**
   * Leave every box unticked to offer this trim package on all floor plans.
   */
  floorPlans?: (number | FloorPlan)[] | null;
  /**
   * Ticked on automatically when a buyer picks this trim package. They can still change any of it.
   */
  defaults?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * One shared library. A product is entered once here and picked by as many trim packages as need it, so a price change lands everywhere at once.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Generated from the name when you first save. Permanent: shared build links encode it.
   */
  slug?: string | null;
  description?: string | null;
  category: number | Category;
  type: 'included' | 'upgrade' | 'addon';
  /**
   * Included: leave at 0. Upgrade: charge the DIFFERENCE over the item it replaces. Add-on: the full price.
   */
  price: number;
  /**
   * Untick to hide this from its category step. It still prices, still shows on the Build Sheet, and still appears in the what-is-included list of any trim package that carries it. For components a buyer has no opinion about, like a 50A versus a 100A charger.
   */
  selectable?: boolean | null;
  image?: (number | null) | Media;
  /**
   * Two upgrades replacing the same item are automatically mutually exclusive.
   */
  replaces?: (number | null) | Product;
  /**
   * Picking this pulls them in. Removing one of them removes this too.
   */
  requires?: (number | Product)[] | null;
  conflictsWith?: (number | Product)[] | null;
  /**
   * Leave empty if it fits every plan.
   */
  availableFor?: (number | FloorPlan)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Generated from the name when you first save. Permanent: shared build links encode it.
   */
  slug?: string | null;
  blurb: string;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pick-exactly-one swatch sets. Every choice is $0 today; the price field exists so a premium finish can charge later without a rebuild.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "color-groups".
 */
export interface ColorGroup {
  id: number;
  name: string;
  /**
   * Generated from the name when you first save. Permanent: shared build links encode it.
   */
  slug?: string | null;
  blurb: string;
  order: number;
  /**
   * Which wizard step these swatches appear on.
   */
  category: number | Category;
  choices: {
    name: string;
    slug: string;
    /**
     * Six-digit hex, e.g. #c8a072.
     */
    hex: string;
    /**
     * Optional second hex. Set it for wood grains to render a two-tone swatch.
     */
    hex2?: string | null;
    price: number;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * Staff accounts for this admin. Create one here with an email and a starting password, then have the person change it under their own account.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'staff';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'van-lengths';
        value: number | VanLength;
      } | null)
    | ({
        relationTo: 'floor-plans';
        value: number | FloorPlan;
      } | null)
    | ({
        relationTo: 'trim-packages';
        value: number | TrimPackage;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'color-groups';
        value: number | ColorGroup;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "van-lengths_select".
 */
export interface VanLengthsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  priceDelta?: T;
  image?: T;
  overallInches?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "floor-plans_select".
 */
export interface FloorPlansSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  basePrice?: T;
  order?: T;
  availableLengths?: T;
  gallery?:
    | T
    | {
        label?: T;
        image?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trim-packages_select".
 */
export interface TrimPackagesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  priceDelta?: T;
  order?: T;
  floorPlans?: T;
  defaults?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  category?: T;
  type?: T;
  price?: T;
  selectable?: T;
  image?: T;
  replaces?: T;
  requires?: T;
  conflictsWith?: T;
  availableFor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  blurb?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "color-groups_select".
 */
export interface ColorGroupsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  blurb?: T;
  order?: T;
  category?: T;
  choices?:
    | T
    | {
        name?: T;
        slug?: T;
        hex?: T;
        hex2?: T;
        price?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}